version: 2.1
workflows:
  build-test-and-deploy:
    jobs:
      - sumologic/workflow-collector # add this job to track workflow.
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
